info:
  component: SpringConfig-Server

server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jordiascension/SpringCloudConfig-Server
application:
  name: springcloudserver
profiles:
  active: dev